# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea204121a18ccc50b65107d4366ef96bc79651264d478e78b28ce2ea959d5fc8b19a248fcd596475751e03eac58d4d28f238172c94c927860e995dc3e2b938e0

test:
  secret_key_base: c814458f07490b8b834ccfb6aca63e22e2bd0cd9c323970a0d4051beb347b3f3bb57aa4e7233fdc2ff5d27d23c50962265fe53355bcfe634da53e59db16bba9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
